"""Add middle name.

Revision ID: 5a33e9538dfa
Revises: dacfb31bf13f
Create Date: 2021-05-03 00:57:16.404184

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5a33e9538dfa"
down_revision = "dacfb31bf13f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ### noqa: ANN201
    op.add_column(
        "student",
        sa.Column("middle_name", sa.String(), server_default="Bob", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ### noqa: ANN201
    op.drop_column("student", "middle_name")
    # ### end Alembic commands ###
